<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_after_logout</name>
   <tag></tag>
   <elementGuidId>84482a84-3915-4180-99d3-cdaa67f2629f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='HyperLink1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#HyperLink1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f68b28d3-d972-4b30-8cfa-342545ad956d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>HyperLink1</value>
      <webElementGuid>0174d892-8997-45f6-bef5-d16b4c713075</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>Login.aspx</value>
      <webElementGuid>c5bdba70-aa23-4e79-a2f4-ab6ac51a2a0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hreftarget</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>b19d8ffc-e84a-4cfc-ba0f-d389d76a71be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>You have been successfully signed out</value>
      <webElementGuid>a63cbad3-9e06-4307-afc4-a384e4e2ed08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;HyperLink1&quot;)</value>
      <webElementGuid>394813c7-59d8-416c-8c7a-f324f3066dbf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='HyperLink1']</value>
      <webElementGuid>3fcfc21d-2b45-4f84-ac48-65d012291333</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[3]/a</value>
      <webElementGuid>3b19dc7d-1e1f-4c83-aa8e-9b9d81cf1042</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'You have been successfully signed out')]</value>
      <webElementGuid>9f347b9e-5c99-4689-8270-1b6ee6490840</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::a[1]</value>
      <webElementGuid>cf9f36c4-e33c-4abb-9a51-08d58ae96b7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::a[1]</value>
      <webElementGuid>b47f7c7b-5854-41d3-bd86-3cdaff165b41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='You have been successfully signed out']/parent::*</value>
      <webElementGuid>c4349069-5385-4450-a373-cfe771b77d9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'Login.aspx')]</value>
      <webElementGuid>bb790ae9-1eac-4f04-94c7-1f6049f1b48b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>07eccf13-16b9-4931-8956-aa7934c81413</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'HyperLink1' and @href = 'Login.aspx' and (text() = 'You have been successfully signed out' or . = 'You have been successfully signed out')]</value>
      <webElementGuid>22cd321d-ea17-41d2-a610-cc5741ba2c1d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
