<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bar_user_id</name>
   <tag></tag>
   <elementGuidId>603ad35f-ba13-4b49-a53b-ce376d58fe49</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='barUserID']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#barUserID</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1386792c-1887-4c4b-a807-e01b50f153b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-toolbar-text x-box-item x-toolbar-item x-toolbar-text-default</value>
      <webElementGuid>c676b4e7-4248-4481-bea2-524c9507511c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>barUserID</value>
      <webElementGuid>eee9bbe9-2597-4654-a10d-536e2c7fe647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>User ID : testmaker1</value>
      <webElementGuid>362aefc5-12b1-44a4-8938-208252d67fc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;barUserID&quot;)</value>
      <webElementGuid>6cf066f4-6355-4c7e-8ef0-cae5ab4b1431</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='barUserID']</value>
      <webElementGuid>385ebfc8-f889-4dcb-8f4c-02ad04720be8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='statusbar-1011-targetEl']/div[3]</value>
      <webElementGuid>42f10be4-ccd5-430a-881f-961d603e35c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AML BTPNS'])[2]/following::div[23]</value>
      <webElementGuid>a321511b-e86c-4907-a85c-eee55ba22f60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AML BTPNS'])[1]/following::div[28]</value>
      <webElementGuid>ed296105-a9c0-4345-9c65-a70d63e7562e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Group Menu : AML maker'])[1]/preceding::div[2]</value>
      <webElementGuid>d0329292-d6cd-477e-bad8-c43124c4d85f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Success Login : 29-Mar-2023 14:58'])[1]/preceding::div[4]</value>
      <webElementGuid>a9efddf0-f826-4e48-b79f-794a61017ca1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='User ID : testmaker1']/parent::*</value>
      <webElementGuid>3b2864bd-333b-4da3-a533-9315fb9511b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[3]</value>
      <webElementGuid>12ba9e43-84ee-47e4-9c65-c0b5f3009cac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'barUserID' and (text() = 'User ID : testmaker1' or . = 'User ID : testmaker1')]</value>
      <webElementGuid>9d3181cd-2538-490d-a194-7f1dd40c8ba7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
